### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by AmirulAndalib** [AmirulAndalib/MLTB-ALPINE-DOCKER#3]
- [ ] Optimize Docker image storage by deleting dependencies

- [ ] Mount Docker Secrets  >> no need since the platform is dead

- [ ] Make a separate branch for Mega SDK **Rest Version** >> under developed and dead repo

- [x] Support for ```linux/amd64,linux/arm64,linux/arm/v7``` architectures
***https://github.com/AmirulAndalib/MLTB-ALPINE-DOCKER/commit/b15369a4f66d406154aab7f4c77d3c6f35df4a07***

- [x] try to make dockerfile as much light as possible for mobile or light use eg Termux Raspberry pi 02W - **512mb** 2-2.5 GB docker image can't lessen more because deleting dependencies crashes megasdk and some important applications on repository but works fine on Low end devices but for 512MB the performance will be around 18% ≅ to heroku's aws 512MB server with 1 GB swap can use zswap on those devices for a bit better performance

**Comment by AmirulAndalib** [comment]
Useless kontol
